services:
  komodo-mcp-server:
    image: ${KOMODO_MCP_IMAGE:-ghcr.io/mp-tool/komodo-mcp-server}:${KOMODO_MCP_IMAGE_TAG:-latest}
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    
    ports:
      - ${KOMODO_MCP_PORT:-8000}:8000

    env_file:
      - .env
    
    volumes:
      - ./.dev/test.config.toml:/app/config.toml
